### ISSUE TITLE
SOD Hot streak not working

### ISSUE THREAD

**Issue by Artimas** [ennvina/spellactivationoverlay#171] opened 2024-02-13 04:57 UTC
hot streak spell ID - 400625
frostfire bolt spell ID - 401502
living bomb spell ID - 400613 -- not sure if that is the dot or the explosion or if it matters.

**Comment by Artimas** [comment] 2024-02-13 15:48
I think lines 42-45 of the mage Lua won’t be necessary anymore, then changing the handler method isspelltracked and hastalent to check for the rune by the spell id of hotstreak will work, but then there will have to be separate files for sod and other game versions. The only other way I thought about is making a separate hotstreak handler for sod and having it in there. Then the load options function will have to included the sod talents and the hotstreakspellID will have to be updated.

**Comment by Artimas** [comment] 2024-02-13 15:50
Also did some testing and I don’t think that spell is for hot streak is right. I’ll figure it out soon. 

P.S. the way it checks for heating up is dope. 10/10

**Comment by tparrott** [comment] 2024-02-16 04:26
Did some testing today. Hotstreak logic appears to be working properly, but the texture for hot streak is missing from the build. I copied hot_streak.blp from the wotlk classic build and added it to ..\World of Warcraft\_classic_era_\Interface\AddOns\SpellActivationOverlay\textures.

You may also copy and rename any of the existing textures to hot_streak.blp and it will simply trigger that texture.

While testing, it appears to trigger properly when the hot streak proc occurs, but I have not seen the heating up (smaller 50% icon when at 1/2 crits) appear. The code references that it's the same texture, so I believe there may be an issue in the actual heating up code.

**Comment by Artimas** [comment] 2024-02-22 23:46
Yeah I think the heating up code first checks if you have it talented and if you don’t it won’t run. And since we don’t have the talents it won’t run. I tried adding in the texture and still wasn’t seeing it but I’ll try it again tonight, if your right I’ll try commenting out the check talent step and test

**Comment by tparrott** [comment] 2024-02-23 13:28
> Yeah I think the heating up code first checks if you have it talented and if you don’t it won’t run.

This makes sense then. I thought it was just a made up function to let you know when you're getting close to the proc. If it's a talent, then I'm sure it'll work properly when unlocked.

**Comment by ennvina** [comment] 2024-03-11 22:09
Hi guys. I was out for a while, thanks @Artimas and @tparrott for keeping things up in my absence :)

## DoT vs. Explosion

Yes it matters to know if the spell ID is for the damage-over-time or the explosion. In Wrath there are two spell IDs, one for the DoT and one for the explostion. In former iterations of the addon, I tracked the wrong one, which messed everything up.

According to my research, in Season of Discovery, [400613](https://www.wowhead.com/classic/spell=400613/living-bomb) is the DoT and [401731](https://www.wowhead.com/classic/spell=401731/living-bomb) is the final damage. If anyone can confirm that would be great.

## Azeroth's got Talent

The Hot Streak code simply check Hot Streak buff - as long as we have the correct spell ID, it should be fine.

Heating Up is a complete different matter. There was no explicit 'Heating Up' buff in Wrath, and I expect SoD to have the same issue. So we have to _guess_ whether we are in a Heating Up state by checking critical strikes from the combat log. But because anyone can crit with a Fireball, we must display the Heating Up effect only for mages who will have a Hot Streak proc if they crit again. so, checking the combat log only is not enough.

This is where the talent check comes in.

The current code is designed for Wrath, where Hot Streak is a talent. Extra caution is made against players who re-spec, in which case the Heating Up effect is 'banked' and restored whenever necessary (not going much more into details for this system, the code and commit messages will tell the full story). This should be fine if we make sure to mimic talent detection code before we write rune detection code.

## Missing Texture

When we added support for Classic Era, there were many textures that were used for Wrath but not for Era. I didn't want Era players to download a bunch of textures they would never use, so I made sure to discard unwanted textures for the 'Vanilla flavor'.

We will simply re-include `hot_streak` from the Vanilla build, and voilà!

**Comment by ennvina** [comment] 2024-03-13 22:07
Hi, I'm closing this issue because Hot Streak and Heating Up have been implemented in #185 and will be included in the next release. Feel free to re-open it if it does not work as intended.

**Closed by ennvina** 2024-03-13 22:07 UTC
Labels: mage, sod
